name: Build and publish to PyPI

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'
      - 'src/cpp/CMakeLists.txt'

jobs:
  # see cibuildwheel github for more
  # matrix built for building on all environments
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-vs2026-arm, macos-15-intel, macos-latest]

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip"

    # build wheels
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.22.0
      with:
        package-dir: .
        output-dir: wheelhouse

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: ./wheelhouse/*.whl

  upload_pypi:
    name: Publish package distributions to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
       id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist 
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
