name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - run: uv sync --group dev

      - run: uv run pytest -m 'not timelimit' -k 'not CPLEX_PY'

      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3

      - name: Upload failed MCES structure SVG
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-structure
          path: "testdata/mces_struct_*.svg"
